import type { BundledLanguage } from "shiki";

const LANGUAGE_MAP: Partial<Record<BundledLanguage, string>> = {
  javascript: "javascript",
  js: "javascript",
  jsx: "javascript",
  typescript: "typescript",
  ts: "typescript",
  tsx: "typescript",
  python: "python",
  py: "python",
  json: "json",
  jsonc: "json",
  markdown: "markdown",
  md: "markdown",
  mdx: "markdown",
  html: "html",
  css: "css",
  scss: "scss",
  less: "less",
  sql: "sql",
  yaml: "yaml",
  yml: "yaml",
  xml: "xml",
  rust: "rust",
  rs: "rust",
  go: "go",
  java: "java",
  kotlin: "kotlin",
  kt: "kotlin",
  ruby: "ruby",
  rb: "ruby",
  php: "php",
  shell: "shell",
  sh: "shell",
  bash: "shell",
  zsh: "shell",
  powershell: "powershell",
  ps1: "powershell",
  csharp: "csharp",
  cs: "csharp",
  cpp: "cpp",
  c: "c",
  swift: "swift",
  lua: "lua",
  r: "r",
  dockerfile: "dockerfile",
  toml: "toml",
  graphql: "graphql",
  gql: "graphql",
};

export function toMonacoLanguage(language: BundledLanguage | string): string {
  const key = language.toLowerCase() as BundledLanguage;
  return LANGUAGE_MAP[key] ?? key;
}
